# Generated by Django 5.1.2 on 2024-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='generate_unique_user_id', editable=False, max_length=50, unique=True),
        ),
    ]
