# Generated by Django 5.1.2 on 2024-10-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
