# Generated by Django 5.1.2 on 2024-10-22 13:45

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_usersprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=Users.models.default_profile_picture, upload_to='profile_pictures'),
        ),
    ]
